### ISSUE TITLE
The ability to use this library in existing code

### ISSUE THREAD

**Issue by ghostiam** [lqs/sqlingo#14]
Hello. 
Please add the ability to use this library in existing code, without opening a connection to the database, but using the existing one.

For example:
```go
var db *sql.DB // already existing connection
sq := sqlingo.Use("mysql", db)
```

If I understand correctly, this fix should suffice:
```go
func Use(driverName string, sqlDB *sql.DB) Database {
	return &database{
		dialect: getDialectFromDriverName(driverName),
		db:      sqlDB,
	}
}
```

**Comment by lqs** [comment]
Thank you for your suggestion. This is now available in `v0.11.2`.
