### ISSUE TITLE
改进意见

### ISSUE THREAD

**Issue by dulumao** [lqs/sqlingo#6]
业务里有几个特殊地方，需要用到db.query,垮了几个表最终查询到数据并不是一个实际表,比如
```go
Table A
akey  avalue

Table B
bkey  bvalue
```

```go
type Item struct {
		Akey    string
		AValue  string
		BKey    string
		BValue  string
		Querytime time.Time
	}
	
	var items []Item

	rows, _ := db.Query(`select total.*, now() as querytime from (select akey, avalue,bkey, bvalue from table_a join table_b) total`)

	for rows.Next() {
		var i Item
		rows.Scan(&i)
		
		items = append(items,i)
	}
	
	//....
```

这种情况很麻烦啊，又没办法用fetchAll 或者 fetchAllAsMap

mysql sql return
![image](https://user-images.githubusercontent.com/2610297/87760628-9c115600-c842-11ea-8d7a-1a41fd11897f.png)

**Comment by lqs** [comment]
这条查询可以改写成：
```db.Select(TableA.GetFields(), TableB.GetFields(), Function("now").From(TableA, TableB).FetchAll(&items)```

**Comment by dulumao** [comment]
@lqs 确实这种是可以解决这个问题，如果可以的话最好是能吧sql.Rows里的columns导出来，这样可以做的事情很多了

**Comment by lqs** [comment]
@dulumao 

可以先用`db.GetDB()`拿到原生的`sql.DB`对象，然后就可以用它来直接查询了。

另外，我考虑设计一套适合动态字段的获取方式，现在暂定设计成这样（还没实现）：
```
for rows.Next() {
        row := rows.Map()
        akey, err := row["akey"].Int()
        avalue, err := row["avalue"].Int()
        println(akey, avalue)
}
```

**Comment by dulumao** [comment]
嗯，这个是不错的，抓紧呀 😄

**Comment by dulumao** [comment]
如果可以顺便弄个读写分离呀，小项目来得省事，不用直接上第三方应用
