### ISSUE TITLE
error in generating code...

### ISSUE THREAD

**Issue by Flipped199** [lqs/sqlingo#7]
D:\Projects\GoProjects\*>sqlingo-gen-mysql root:flipped199@/lover-bind >model/user2.go
Generating user
panic: 4:14: expected ';', found '-'

goroutine 1 [running]:
main.main()
        C:/Users/Administrator/go/pkg/mod/github.com/lqs/sqlingo@v0.10.7/sqlingo-gen-mysql/main.go:12 +0xf1

D:\Projects\GoProjects\*>

ddl is ok.

**Comment by lqs** [comment]
有可能是字段名里有特殊字符，可以把建表语句（SHOW CREATE TABLE user）发来看一下吗？

**Comment by lqs** [comment]
应该是数据库名里有横杠导致的，问题已修复，请更新到最新版（`go get -u github.com/lqs/sqlingo/sqlingo-gen-mysql`）
