### ISSUE TITLE
Error generated DSL

### ISSUE THREAD

**Issue by ansidev** [lqs/sqlingo#8]
Errors:

1.

```
undefined: ufloat64
```

Generated sample code:
```
type SampleModel struct {
    Id             uint32
    DoubleValue    ufloat64
}
```

2.
```
Field is not a type
```

Generated sample code:
```
type Field interface {
    Expression
    GetTable() Table
}
```

DB: MariaDB 10.x

**Comment by lqs** [comment]
You could workaround these by
1. Remove the `UNSIGNED` and `ZEROFILL` attributes on the "double_value" field
2. Change the table named "field" to another name

We will improve the generator to deal with these cases in next version.
