### ISSUE TITLE
Null handling

### ISSUE THREAD

**Issue by edrobinson** [lqs/sqlingo#9]
Trying out sqlingo this afternoon on a mysql database with lots of nulls and sqlingo complains:

"read C:\users\ed\gostuff\sqlingotest\generated\sqlingo\jake2.dsl.go: unexpected NUL in input"

Looks like a nice tool set. Is it not built to handle nulls?

**Comment by lqs** [comment]
It seems that the generated `jake2.dsl.go` was saved in a different encoding and go cannot compile it as source code. Please try to rerun again in `cmd` (not PowerShell)

**Comment by edrobinson** [comment]
I regenerated the jake2.dsl.go using win cmd. I am trying to run this go:

package main

import (
    "github.com/lqs/sqlingo"
    . "./generated/sqlingo"
)

func main() {
    db, err := sqlingo.Open("mysql", "root:@tcp(localhost:3306)/jake2")
    if err != nil {
        panic(err)
    }

    // a simple query
    db.SelectFrom(drivers).
        Where(driver.Id.In(1,2)).
        OrderBy(driver.LastName.Desc()).
        FetchAll(&drivers)
}

Now I get this error:

build command-line-arguments: cannot find module for path _/C_/users/ed/gostuff/sqlingotest/generated/sqlingo
